# Get OSP Server Instance Information
- name: OpenStack servers
  os_server_facts:
    cloud: ospcloud
  register: openstack_servers
  tags:
    - cleanup

# Remove OSP Instances
- name: Remove Openstack Server Instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
    image: rhel-guest
    flavor: m2.small
    delete_fip: true
  with_items:
  - "{{ openstack_servers}}"
  tags:
  - cleanup
