---

#- name: cleanup the 3-tier application
#  hosts: all
#  gather_facts: false
3  become: true
#  roles:
#    - { role: "./roles/cleaner" }

- name: generate dynamic inventory
  hosts: jumpbox
  roles:
  - inventory-setup

- name: install repo on all hosts
  hosts: all
  become: yes
  gather_facts: false
  roles:
  - destroy-vm
